### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by jinlu2010** [stdying/flutter_rust#1]
Invalid argument(s): Failed to load dynamic library 'libnative_rust.so': dlopen failed: library "libnative_rust.so" not found

**Comment by stdying** [comment]
> Invalid argument(s): Failed to load dynamic library 'libnative_rust.so': dlopen failed: library "libnative_rust.so" not found

用的真机还是模拟器？

**Comment by jinlu2010** [comment]
模拟器，已经解决，需要生x86的so，不是x86_64
